### ISSUE TITLE
Customer Request - Notifications

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#10]
**Is your feature request related to a problem? Please describe.**
No Issue

**Describe the solution you'd like**
I would like once I've "completed" a training that I get a text that says I have completed "x" amount of training for calendar year

**Describe alternatives you've considered**
We print out the reports, but another notification method is nice.

**Comment by tfremming1** [comment]
This came up during some overviews.  I said no guarantees on it getting done or when, but I'd log and we'd discuss in future.

**Comment by Sikta** [comment]
I’ll respond to your stuff tonight. I should have first phase of upload
done after a couple more nights of work.

**Comment by tfremming1** [comment]
no worries I know you're busy :)

I should have everything out of Trello by end of weekend.

On Jan 11, 2019, at 08:44 AM, Lee Olsen <notifications@github.com> wrote:

I’ll respond to your stuff tonight. I should have first phase of upload
done after a couple more nights of work.
