### ISSUE TITLE
Non Admin Login Privileges Part 1

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#104]
This will evolve but initially

1) If non-Admin I can log in

a) Access Trainings (View Only)
b) Ability to get to Admin-Staff (but only see my name)
c) Detail (View Only)
d) Ability to Add Certificates
e) Ability to access Personnel Medical Tab upload documents (just me user signed in) (coming later)

**Comment by Sikta** [comment]
d) Ability to Add Certificates

Delete them too?

**Comment by tfremming1** [comment]
No Deleting as a non-admin
