### ISSUE TITLE
Overflow of Hours - ISO

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#107]
If Officer Training, Facility, Driver, Hazmat exceed the required hours for the year then overages go into company training.

**Comment by Sikta** [comment]
~~Does Driver mean Driver/Operator or New Driver or both?~~

Nevermind on this first question. I added a column to IsoCategory table where this is now configurable. If you want a categories overages to apply to company training, you'll set the "IsOverageCredited" column for that category to "true" in the database.

**Comment by Sikta** [comment]
For the ones that don't have the overage apply to company training, if there is an overage do you want it to show the overage or just show the amount required? IE does PrePlan review show 4 completed out of 1 required or 1 completed out of 1 required if they did 4 hours of PrePlan?

**Comment by tfremming1** [comment]
Driver operator. Not new driver. 

For overages on others they can show more like they can stop at 100% unless that is a big change.
