### ISSUE TITLE
Admin provision logins

### ISSUE THREAD

**Issue by Sikta** [IncidentManagementSystems/ims-issue-tracker#109]
**Is your feature request related to a problem? Please describe.**
As an Admin, I don't want to have to submit requests for user logins when adding a new firefighter.

**Describe the solution you'd like**
In my staff detail screen, I'd like to have a button to provision a login for the staff member.

**Additional context**
Probably need to be able to add staff that are "active" but not show up as available to select in the roster section of a training due to being in an HR type of role. Then these users can be provisioned a login as well.

**Comment by tfremming1** [comment]
@Sikta Everything seems to work ok - if they don't want to create a login (how JFD is today) you have to put an email address in and then click save again.  Is there a better way to do this?  Maybe another button that says create w/o login?

Thoughts?
