### ISSUE TITLE
Topics listed upon creation of training 

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#113]
When I create a training topics from previous session/drill are there by default that shouldn’t be.

Essentially If I create 

Training 1 that is Category Extrication give it A,B,C,D Topics

Create

Training 2 that is Category Roll in, the Topics from Extrication A,B,C,D are there.

**Comment by Sikta** [comment]
Can you add some more info such as what training id you are expecting the
default to come from and what you are entering for training type/category?
The more detail provided the quicker I can get to the root issue when I
have a moment to look at this.

**Comment by tfremming1** [comment]
The bug is that there is default topics coming in.

1) Create a new drill add an ISO topic
2) Create a 2nd new drill the topic from Drill 1 will be there by default (shouldn't be should be clean slate)
