### ISSUE TITLE
Non - Admin User (Training)

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#121]
Sorry this needs to be done or I worry about data integrity issues and if we have those we'll lose trust.

As a non-admin I should not be able to unlock a training.

**Comment by Sikta** [comment]
If that isn’t how it is already working then it’s a bug. Only admin should
be able to unlock. I know we have code for that. I’ll check it out in a
little bit.

**Comment by tfremming1** [comment]
No I just tried it with my (non admin user) in PROD and I can unlock it, change stuff and save (can’t complete but I can alter it and save)

**Comment by Sikta** [comment]
Yep, must’ve happened when I redid that UI with tabs. It’ll be an easy fix.
