### ISSUE TITLE
Enabling Create User

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#130]
As an Admin, when I create a new member of a FD I need it to automatically tie it into its profile and??? auto generate a password.

Instead of how we manually set it up today, this would empower the admin to do this all through a UI interface.

**Comment by Sikta** [comment]
https://github.com/IncidentManagementSystems/ims-issue-tracker/issues/109

I had already created a story for this. Closing this one as duplicate.
