### ISSUE TITLE
Hazerdous Materials and Mixed Use Fields

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#139]
Hazardous Materials and Mixed Use - Text needs to be longer in db.  Also They need the number at the front like Primary Action, Incident Type, Property Use.

**Comment by Sikta** [comment]
I was able to fit everything into the tables as is for these 2. That was how I chose the size of the column.

**Comment by Sikta** [comment]
Add the ID to the text in the dropdown.
