### ISSUE TITLE
Staff Tab - Clicking on Fire Fighter Name - Main Display

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#14]
DESIGN NOTE - Lets be sure to leave a breadcrumb link in this example
Admin -- Staff -- Active -- Fire Fighter --Details

NOTE - Same views for past fire fighters as well.

This would display in a "module" with 3 tabs this being the "main display"

NOTE - Years of Service will be used in a report that will list out:
~First Name~, ~Last Name~, Address, Hire Date, Years of Service

Note what is listed below is also the label:

Address
~Miles to Station (maybe we can incorporate a google plugin at some point) - does not need to work in this first iteration~
~Date of Birth~
~Hire Date~
~Adjusted Hire Date (if Rehired)~
~End Service Date~
~FDID (should default to who is logged in) and not editable~
~Status (create so I can add options e.g. Active, Not Active, Leave, Retired) - If Not Active display only in non-active section~
~Years of Service (Calculation from Hire Date or Adjusted hire Date)~
~Phone Number~
~Email Address~
~Rank (Drop Down) Chief, Assistant Chief, Captain, Lieutenant, Fire Fighter~
~Type: Career or Volunteer (options)~
~Fire Number~

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/0c5c61a5-0812-46c2-8f8c-46f61fdc1541)

@Sikta I noticed I missed "adding" So we'll need a button for "add" to add a new with the information listed above.

**Comment by Sikta** [comment]
Which of these values are required?

I'm thinking I'm gonna do Active/Inactive as a toggle but if you select Inactive you'll get a dropdown for "Reason" with the other choices. It was made as a toggle in the previous story since it never said anything about other states. Would require changing a lot of that other stuff if we changed the type.

Is rank a standard or should it be customizable per fire department?

Should type be customizable per fire department?

**Comment by Sikta** [comment]
Do you want Fire Number, Training Rate, Incident Rate to also be on this screen?

**Comment by Sikta** [comment]
Are they hand entering in the miles to station for now or is it going to remain empty until we add the ability to calculate it?

**Comment by tfremming1** [comment]
Lee - First comment yes do the easy button way, no big changes.  Also when we deactivate we'll need a deactivate day logged in dB.

Rank should have default values of Lieutenant, Captain, Assistant Chief, Chief.  Shouldn't have to customize this.

Type is just Volunteer / Career

Yes on the Fire #, Training Rate etc. on this screen as well.

Miles to Station just leave blank for now until ability to calculate it.  If they want to hand enter it that's fine in short term.

**Comment by Sikta** [comment]
Deactivated day is separate from "End Service Date"?

**Comment by tfremming1** [comment]
They are the same.

**Comment by Sikta** [comment]
Hopefully this is the last question on this story.

Is this the correct "Years of Service" calculation?
BeginDate = AdjustedStartDate unless empty then StartDate
EndDate = EndDate unless empty then CurrentDate

YearsOfService = EndDate - BeginDate?

I'm assuming that is correct.

**Comment by tfremming1** [comment]
Yes sir that looks right :)
