### ISSUE TITLE
Authorizations

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#141]
Authorizations - Officer Assignment Tag should read Position or Rank

**Comment by Sikta** [comment]
https://github.com/IncidentManagementSystems/ims-issue-tracker/issues/47

Assignment is separate from Position/Rank. We don't show Position/Rank cause it's already captured in staff detail and will be filled out in the report.

**Comment by tfremming1** [comment]
Thanks for clarifying!
