### ISSUE TITLE
Training - Category not updating after "completed"

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#164]
Create A Training
Complete a Training
Unlock a Training
Try changing the Category
Save (shows saved)
Click complete

Reverts back to original item.

If it matters this was created by a non admin - saved, then finished/completed by admin then unlocking by admin

**Comment by Sikta** [comment]
A) nothing to do with unlock. Happens when editing a training no matter the prior steps.
B) happens on method/type as well

Issue is in the trainingMapping.js file as it's mapping from the category.id instead of categoryId.

**Comment by tfremming1** [comment]
Thanks I just tried to be as descriptive as I could as I recreated from what he said.
