### ISSUE TITLE
Bugs Add Person/Entitiy

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#170]
It is missing this requirement: 

Additional information on the web site that doesn't get put on the output but stored in dB
-Need a mechanism for each person to click "additional info" and let you add Car Make/Model, VIN #, Insurance Provider, Policy number (none of which are mandatory)

Also it doesn't say last name it says first name 2x

Lastly as you know you cannot delete

**Comment by rkiran34** [comment]
Can the car make/model be free form text fields or do they need to be drop downs? If they need to be drop downs, do you guys know if there is a public API that can get that information so we can populate the drop downs?

**Comment by Sikta** [comment]
Let’s just go with free form text fields for now.

**Comment by tfremming1** [comment]
All free form
