### ISSUE TITLE
Hours Attended & Training Hours

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#171]
This is a miss on my part.  IF there is a time adjustment both Training hours and Hours attended should match.  Right now the Training hours is just taking that of what was on the drill.  However when tracking # of hours the individual has done for training for the year it should match the hours attended.

**Comment by Sikta** [comment]
Can you post an image/excel with an example detailed of where you expect a different value and what that value is. I could probably figure it out but it seems you already know exactly and can just give me that example.

**Comment by tfremming1** [comment]
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/2659365c-da97-41da-89e3-a79c053289ba)

**Comment by tfremming1** [comment]
Basically he was a time adjustment so his hours attended is correct, but training hours should = hours attended

**Comment by Sikta** [comment]
I guess I don't understand why 2 columns then. When I built this, I assumed the first column was intended to allow someone looking at the report to be able to see they didn't attend the entire training. If the value is supposed to be the same as the next column then I don't understand the reason for 2 columns.

**Comment by Sikta** [comment]
When trying to track how many training hours someone has accrued....use "Hours Attended"?

**Comment by tfremming1** [comment]
I agree it was an oversight on my part We are tracking 2 correct things.  # of Training Hours, Payroll hours.  I"m not sure why I thought it had to be different.

**Comment by tfremming1** [comment]
When trying to track how many training hours someone has accrued....use "Hours Attended"?

Correct

**Comment by Sikta** [comment]
Wait....is this report supposed to show 0 for "Hours Attended" if it's an unpaid training? I don't know if it does that or not.

**Comment by Sikta** [comment]
Ah the "Paid" column determines that. I think I should just remove one of the columns and display the "Hours Attended" value?

**Comment by tfremming1** [comment]
Yes that sounds easiest
