### ISSUE TITLE
Payroll Report

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#173]
Report should be for fire department logged in as.
Report should be for dates requested in UI
Report Querty, Lastname, Firstname, is paid (yes)
Report output

Lastname, Firstname, Sum Total Hours Attended

Example
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/37ff518d-27f8-4183-b247-7d4e6dc1fa0f)

**Comment by Sikta** [comment]
Does this need to be "Training Total" as I assume there will be another column with "Incidents Total" once we have Incidents completed (I believe they pay different rates?)?

**Comment by tfremming1** [comment]
Yes training total. Thank you for clarifying.
