### ISSUE TITLE
Fire Fighter Training % Report

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#174]
In the UI when selecting this report we need an option to add how many drills.

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/497c26a5-d9f0-45ae-9574-39f653f3be03)

When I run the report we need it to calculate % based off of Regular Drills, Makeup Drills.

So If I put in Dates of July 1 - September 30 and number of drills = 12

The report would look something like this:
Lastname, Firstname, % Calculation
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/e79b69af-e1a0-419b-89eb-6221f6fd387f)

**Comment by Sikta** [comment]
Why are they entering the # of drills? Don't we know how many there were between those dates based on what they've entered into the system?

**Comment by tfremming1** [comment]
If you are telling me that if I put in Jan 1 and April 1 and i have had 10 drills logged and I only attended 5 that the report will tell me 50% I’m cool with that.

**Comment by Sikta** [comment]
That's what I'd expect. If they have to manually count those drills and enter it themselves, I'd expect there to be possibility of mistakes. If we just count up the total number of "drills" (is this a sub-category of trainings or all trainings) that should maintain the accuracy of the report. The only way it could be the other way around is if they aren't counting certain drills based on data we don't have in the system or if there are drills that aren't logged for whatever reason (attended a different fire departments drill, etc).

**Comment by tfremming1** [comment]
Cool. I have real savage data I can use to test with so that works for me
