### ISSUE TITLE
ISO - Probationary Fire Fighter/Officer

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#175]
If FF is Probationary based on RANK in Staff the New Recruit Training should be displayed on staff detail ISO
If FF is anything but Probationary based on RANK in staff New Recruit Training should NOT display on staff detail ISO

If Rank = Probationary and/Or Fire Fighter -  Officer ISO should not display.  Officer ISO should only display for Lieutenant, Captain, Assistant Chief, Chief

NOTE - Probationary to be added to deployment scripts to display in drop down

**Comment by rkiran34** [comment]
@tfremming1 - 
1. Should the core elements tab be displayed for Probationary Officer and FireFighter(FF)?
2. What happens when you are creating roster for a training? Should a PO and FF not be allowed to be picked for a training? If they are not allowed to be added to a training, then they will not show up in the ISO and core elements tabs' available attendees(which I am assuming is what is required).

**Comment by tfremming1** [comment]
1- yes it should show up 
2- anyone can be chosen for training 

What I am wanting to show is in iso new recruit training displays. This is training outside of the fd  if you are no longer probationary that iso can be removed from display as it’s no longer relevant 

Lmk if that makes sense

**Comment by Sikta** [comment]
Do you only go from probationary to FF starting on Jan 1? If not, then the assumption is you are only taken off probationary because you completed the new recruit training and it’s no longer relevant to show?

**Comment by Sikta** [comment]
If you get promoted to officer in say September, are you still expected to complete a years worth of officer training in those 3 months?

**Comment by tfremming1** [comment]
Right the admin would make the change. Every dept is different. Like the probationary guys that started in August won’t be done with their training till February.  At some point the department protocol will have them switch off of probationary.

**Comment by Sikta** [comment]
Seems to me that new recruit training should be tracked separately from ISO then. It’s gonna show 0 hours completed come Jan 1.

**Comment by tfremming1** [comment]
“Most” officers get promoted Jan 1 but there are exceptions. Are they required to complete the 12 hours if hired mid year..... that again would depend on dept   But if the admin changes Their role to an officer mid year then the officer bucket shows up

**Comment by tfremming1** [comment]
They can look at previous year and see what it was and current year. It’s a mechanism to track it. As long as they see both before they are done with that kind of training all is well

**Comment by rkiran34** [comment]
This is what I'm understanding we need to do. Let me know if i'm wrong - 
1. If agent is FF or PO, in the staff detail ISO tab display one card that says "New Recruit Training"  (If this is the case what should we put for Hours Completed and Hours Required on that card?)
2. Nothing else changes in the Trainings page. Even though the FF or PO can be selected for regular ISO trainings, those will not be displayed in the Staff detail page for the respective FF and PO.

**Comment by Sikta** [comment]
Staff Detail ISO Tab
Cards:
New Recruit - Only displays if agent is probationary rank
Officer - Only displays if agent is Lieutenant, Captain, Assistant Chief, Chief (> FF)
All Other Cards - Displays always

Training
No changes

**Comment by Sikta** [comment]
That is how I'm understanding this story

**Comment by rkiran34** [comment]
Ok, I did not understand that Officer ISO is a separate ISO training like New Recruit training. So the current ISO cards will be displayed only when the agent is FF.
Then what are the required and completed hours for "New Recruit" and "Officer" and how are the completed hours tracked? If we are not tracking those hours is there a point in showing the card and will it be enough to not display the ISO tab for anyone other than an FF?

**Comment by tfremming1** [comment]
This seems like it has been made way more complicated than need be

1). If probationary also show new recruit training and allow it to be tracked. 

1a if not probationary do not show card

2) if officer show the officer card
2a if not officer do not show card

Nothing else changes. It is all about what visually we are showing based on rank

**Comment by Sikta** [comment]
Ravi these cards already exist. This story is just about whether to display them based on rank.

**Comment by rkiran34** [comment]
Thanks Lee, that helps. Since I was working with my local database, I did not know that those IsoTopics exist.

**Comment by tfremming1** [comment]
@rkiran34 @Sikta Need access to test dB again to add this to drop down to test.  Once I get that from Lee I will finish this up.  Everything else is looking good.
