### ISSUE TITLE
Create Incident Manually

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#2]
#3 
As a user I want to be able to click "Create New" on Incidents and have a new incident created.

- It should increment my incident number by 1
- The Basic information screen should display

For the test site or ID #1 start the numbering off at 19-0000001 This way when testing I can validate the increments.  Please note per our discussion multiple FDs can have the same number, the differentiating point will be the FDID.

**Comment by Sikta** [comment]
Is the 19 in "19-0000001" the FDID?

**Comment by tfremming1** [comment]
19 is the year.
