### ISSUE TITLE
"Fix" issue if time starts on day X and goes to Day Y

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#200]
Currently if you Log something that starts on day X at lets say 2200 hrs and it ends on day Y at 0200 hours the system is putting in the time of -20 hours instead of 4 hours

We need to be able to count them as positive hours.  

This will happen more with incidents than training's, but I would like to get it worked out and fixed now.

Maybe "if" this scenario happens it asks for end date?  We haven't determined how we are going to calculate incidents yet, but it'll likely be off of call time and "end time" which all have date pickers right now

**Comment by Sikta** [comment]
This should already work for incidents as we allow them to pick the date on
each of those times for this very reason. We didn’t do that for training
because I was told a training would never stretch past midnight.

**Comment by tfremming1** [comment]
Ok so shelve it for now as it’s not really and issue it should we change training to date time picker?
