### ISSUE TITLE
11 Core Element Change in Reporting

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#210]
Instead of putting in a time for 11 core elements please change it to simply just selecting the element.  I just have to click on it to "engage it" to know that I worked on some part of that within the element.

Another story coming about mapping elements to ISO so please keep in mind when making this change.

Follow up story to this will be how to report on this.

**Comment by Sikta** [comment]
To make sure I'm understanding this, you know longer are entering time spend on 11 core elements? We just apply the total training time to all selected elements?

**Comment by tfremming1** [comment]
Correct the state Fire Marshall confirmed this for me over weekend.
