### ISSUE TITLE
Training - Add to Training Screen

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#24]
Add cumulative time in db for training session in 15 min increments.

So if Training was 1700 - 1900 2 hours would be added in row as well.
Tracking the hours like this will help with reporting for payroll -- done

Type: Drop Down: Regular Drill, Makeup Drill, Continuing Education -- in progress
NOTE - Rename other "Type" to "Category" -- done

Label "Paid" Checkbox:  Paid (On by default) will have to update db if unchecked -- done

Show Fire Fighters Alphabetically -- done

When selecting other in "Category" let it be a free text box to enter in some text -- done

When Training is marked as "completed" please leave on main training screen showing "completed" with ability to go into look at but not edit.  I believe we had it like this before.   -- done

Re-label upload to "lesson plan" -- done

**Comment by Sikta** [comment]
"When selecting other in "Category" let it be a free text box to enter in some text" -- what do you think about making this work like https://react.semantic-ui.com/modules/dropdown/#usage-allow-additions? I can then either persist that manually typed category to the database for future use by the fire station or leave it just for the session (persisting it as an option always would actually be less work I think). I'd do a popup validating they want to add it just to give them a chance to clear in case of a typo.

**Comment by tfremming1** [comment]
Lets do the one with less work.  I'm good with that.
