### ISSUE TITLE
Training > Detail Tab

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#267]
Add A checkbox to the Detail Tab called "Includes EMT/EMR"

-Unchecked by default
-When checked and user clicks "save" a new tab for EMT/EMR displays

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/a81a8277-f668-4a59-9c2c-ee100848015d)

**Comment by rkiran34** [comment]
@tfremming1 - what are we trying to achieve here? Is it that a training covers multiple categories and we have to split the training time across these different categories?

**Comment by tfremming1** [comment]
Right now we cover Fire Training, Structure Fire Training etc.   During each training session it is possible that medical is getting covered.

So we are going to track medical training along with fire training as there is a 2 year mandate on training hours for EMR or EMT.  This allows us to in the same screen now track that.  There are only two new items on this screen  EMR/EMT Category and time for that category, which is independent of the "total" training hours.

This will lead into the other stories I referenced - 264 and 96.

So with one training records we can cover core details, fire, medical, ISO, 11 Core elements, attendence payroll etc.  This makes this a very powerful 1 stop shop for us.

**Comment by tfremming1** [comment]
I commented directly on item.

**Comment by rkiran34** [comment]
Do the categories you listed apply to all agencies? And if someone adds a new EMR category, does it apply to all agencies or just the agency they belong to (like the Fire category)?

**Comment by rkiran34** [comment]
I guess that is just for the Training method, never mind my previous question.

**Comment by tfremming1** [comment]
Default all agencies if agency 1 adds one it does not show up for agency 2. Same as the fire one.

**Comment by tfremming1** [comment]
@rkiran34 @Sikta 

Updated this page so that it is only the check box that the user needs to select if there is a medical component to training.  Will update other two stories as discussed with Lee
