### ISSUE TITLE
Fire Department - Stations

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#272]
This is an addition as it will feed into the Scheduling, Staff, and some other things down the road.

Change Number of Stations to "Stations"

If Multiple Stations checked then display  "View/Edit" box

Clicking View/Edit will take you to a stations sub tab page

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/ec06ab4c-3476-4b6d-a78a-f26d907d83c2)

**Comment by tfremming1** [comment]
@Sikta updated this page per our discussion

**Comment by rkiran34** [comment]
@tfremming1 - I see that all stories related to Stations are in Core Product pipeline.  Should this go back to Core product as well?

**Comment by tfremming1** [comment]
Everything should be in the backlog pipeline.
