### ISSUE TITLE
Type = School Admin Drop down

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#284]
In the Drop down there will be 3 new options

1. When clicking on Personnel it will lead you to a landing page that will display
2. When clicking on Classes it will bring you to a classes page
3. When clicking on Props it will bring you to the Props Page
4. (new) Replace Fire Department with "School" - same detail just named differently.

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/cb508871-bcde-44fc-8931-82f152825670)

**Comment by Sikta** [comment]
Don't we need an option for `School` where you can modify the school details and add Fire Departments? I'm expecting this would be the same as the Fire Department detail and Stations tab with new labels.

**Comment by tfremming1** [comment]
Yes miss on my part you would need that "School" in place of Fire Department
