### ISSUE TITLE
Add Email to Admin - Staff

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#285]
Add button for emailing staff/students 

Would work same for FD Version and School Version

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/ac6cd78c-868d-4467-8f63-a36cd6005c32)

**Comment by Sikta** [comment]
You want this to email everyone in active staff always?

**Comment by tfremming1** [comment]
Yes that seemed like what would be most mvp
