### ISSUE TITLE
Email end user

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#287]
From:  noreply@incidentsms.com [DO NOT REPLY TO THIS EMAIL]
Subject: [from form]

Details: [details from submission]

Email sent by: [Person who sent email]
Sent from Incident Management Systems

**Comment by Sikta** [comment]
This is the body of the email or separate feature from Email Staff?

**Comment by tfremming1** [comment]
This is what the email looks like to the end user

**Comment by tfremming1** [comment]
@Sikta updated per discussion
