### ISSUE TITLE
EMT/EMR Hours Report

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#290]
Report should be for dates requested and display the Name, EMR/EMT Category and number of hours per category  If Custom Categories were added it should also show those.

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/a6025ec3-3306-4f23-9093-631ca8f36341)

**Comment by rkiran34** [comment]
@tfremming1 - Should the categories be in the report if the training hours amounts to 0?

**Comment by tfremming1** [comment]
Yes they can. Thanks for asking

**Comment by tfremming1** [comment]
@rkiran34 this is in test, but it fails to download, cannot test it out.
