### ISSUE TITLE
Admin- School - Students Landing Page

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#295]
There is a search now

1.  By Last Name
2.  By Fire Department
3.  Emailing "Staff" Is disabled on this screen

Adding is the same as before (Add Screen different Story)

Cards

1. Will show name
2. Will show Fire Department

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/f87ab882-fd81-4a2d-940e-21f045d50ac3)

**Comment by Sikta** [comment]
We added the `email staff` feature so that they can email class attendees. If we only have it on the instructors page then they can't email the students once we convert them to a school agency type.

**Comment by tfremming1** [comment]
So we can't have it email students and instructors as it's currently setup just one or the other?

**Comment by Sikta** [comment]
We'll have to make changes to the email to do that. Which is fine but the story specifically only called for deactivating the email staff button and nothing about an email students button.

I'm thinking emailing should just be in a few spots and context aware. Email from instructors page would email instructors. Emailing from student list page would email all students unless a filter is applied like cutting down to a specific fire department. Emailing from a training/class would email everyone listed to attend.
