### ISSUE TITLE
Students - Add - Detail

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#297]
Student Detail page will largely be like the current page with a few changes

1. Admin will still be able to create Logins
2. Top Items will be similar e.g. Transcripts, Certificates etc.
2a. - Transcript = Classes they were a part of (just like trainings)
2b. - Certificates = Any Certificates issued by IMS for them

NOTE - Street and Postal Code Not Required - Everything else is

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/846d7de0-d2a5-496f-8ebe-0d254920eac4)

**Comment by Sikta** [comment]
Fire Department should be a dropdown with the same options as the dropdown from the list pages filter. It'll be populated from the "stations/fd's" they enter on the additional tab on schoolDetail (agencyDetail).
