### ISSUE TITLE
Free Tier in Azure vs. Step up

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#30]
Investigate free tier in Azure - is first time because it might be "off" - this is ok for now just need to understand if that's the case and if we go up a tier what does cost look like.

**Comment by Sikta** [comment]
We are going to have to step up a tier when I setup the domain name anyways. They don't support that in the free tier.

**Comment by tfremming1** [comment]
Is that when cost kicks in?
