### ISSUE TITLE
Icon's for Home and Splash Screen

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#31]
Travis to have created, - Lee to Implement

192x192 pixels for the home screen icon
512x512 pixels for the splash screen

**Comment by tfremming1** [comment]
I'm not sure which ones you want or style so I'm attaching all 4

![512 x512 PNG (2).png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/6a2a4272-5826-48fe-9ee7-6bd56be30d89)![1092 x 192 png (1).png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/ceca9d07-46b3-44de-b916-a51ab3bf29a3)

![1092 x 192 png (1).png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/c02f1811-5582-4a0f-92a5-b8f263c67f91)

![512 (2) (Custom).jpg](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/1da3fbfd-af25-4916-91db-a7a29fc4a974)

![192 (1).jpg](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/cfa16904-5f64-4d6b-b97d-1cad848c517d)

**Comment by Sikta** [comment]
This is done and should show up on next deployment.
