### ISSUE TITLE
Cannot Save Training

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#32]
When clicking Save error occurs

Access to XMLHttpRequest at 'https://ims-api.azurewebsites.net/api/Trainings' from origin 'https://incidentmanagementsystems.azurewebsites.net' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by Sikta** [comment]
Fixed. Added Content-Type as an allowed header (was ContentType).
