### ISSUE TITLE
Incidents - Section K1 - Person Entity Involved

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#43]
This section needs the ability to start with 1 , but add 1 to many.  If person/entity had previously been entered when starting to enter information it would pre-populate automatically.

Definition
The full name of the company or agency occupying, managing, or leasing the property where the incident
occurred

*Additional information on the web site that doesn't get put on the output but stored in dB
-Need a mechanism for each person to click "additional info" and let you add Car Make/Model, VIN #, Insurance Provider, Policy number  (none of which are mandatory)

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/a58468cb-317c-4ad1-b958-ff661d2b2d0b)

**Comment by rkiran34** [comment]
@tfremming1  - Is the address captured the person's address or the incident location address? Reason I ask is this - when additional entities need to be added - what information should be captured - Is it enough to capture a person's name and phone number or should we capture all fields (business name/phone number/person's name/address)?

**Comment by tfremming1** [comment]
@rkiran34 Ravi - not always will it be the same.  But if you look at the image above there is a checkbox that says is this the same address as Location or in our case the Info Tab section.  Then all you'd need to add is the name of the person, phone number and continue.  

To your other question we need to capture what the image is showing.

Also if more than 1 person involved then we need to add another.

**Comment by rkiran34** [comment]
My question was - when we add multiple people, should we also capture the address and phone number for each one of those? Or does the address and phone number for the first person apply to all persons that we add?

**Comment by tfremming1** [comment]
Address for all

**Comment by rkiran34** [comment]
To clarify - one address for all people. So we just need to capture the names and phone numbers of other people involved?

**Comment by Sikta** [comment]
Think of it like this Ravi. 

If the incident were a Car accident then the incident location would likely be a random location. The people involved are probably going to be 2 different people who live at 2 different locations.

If the incident is a fire, there is a good chance the people involved are living in the location of the incident so all people would share that address.

The form supports this through the use of the checkboxes.

**Comment by Sikta** [comment]
Not sure if the car accident example would really apply but some scenario like that where the incident is in one location and the people involved don't live at the incident location and don't live together.

**Comment by tfremming1** [comment]
Yes a car accident is the right scenario. 

We had a 4 car accident and we had to take down all 4 names and addresses.

**Comment by rkiran34** [comment]
Alright, makes sense. Thanks for the clarifications.

**Comment by tfremming1** [comment]
@rkiran34 This rule applies for both K1 and K2

The type of information required for the fields in this block are the same as those in Block K1 above. The example shown in Block K1 is also applicable to the following Block K2 fields. 

The supplemental form just looks like this which is the same data over and over for as many as needed.

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/b77f0bd1-7b1c-4644-9a44-316798d16fd0)
