### ISSUE TITLE
ISO - Page

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#50]
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/087bce27-8459-4dbb-b7d2-e2724306c597)

)ISO Page should only display those FFs that attended the drill

Topics Cont...
Adding the Hours in the appropriate section will add up in the correct categories in the ISO section.

Future Thought - will be able to save what is checked off by "type" of drill such that if similar drill done in future items are pre-filled.

**Comment by Sikta** [comment]
![image](https://user-images.githubusercontent.com/8400042/56088497-ba222680-5e47-11e9-86d3-5a5f5f419c2b.png)

I think we should start with something a little simpler that will work on mobile/tablet as well to begin with. The dropdown will have "All" as the default but then a list of the attendees to select as well. We can indicate somehow in the dropdown which ones don't exactly match the "All" one. I don't think the UI in the original post will work on a mobile/tablet device.

**Comment by tfremming1** [comment]
Let’s try it and see how it looks.

**Comment by Sikta** [comment]
Try which version?

**Comment by tfremming1** [comment]
Sorry your version thy you are suggesting

**Comment by tfremming1** [comment]
Lee - I am going to add the story for this such that if I do a type = X that when I complete the ISO on it, the next time I do that kind of type it is all predefined for me.  I can modify it as such but I think it's a good first step.

**Comment by Sikta** [comment]
When I create a training, does it automatically get this prebuilt ISO values from previous training of the same type? And then if I add Attendees, do they automatically get those ISO values? So if I never even so much as visit the ISO tab, everyone will get the same ISO credit as the last training of the same type?

This concerns me a little. What if Training 1 is 2 hours of training, then the next time there is a training of the same type it is 8 hours of training? I wouldn't expect the ISO values to be the same yet that would happen if they don't even look at the ISO tab.

**Comment by tfremming1** [comment]
I do not expect the values to be the same, but how you have it set up wtih topics yes.  Extrication will always be the same topics, Class A burn etc.  The time will be different however as will the people who attended the training.

**Comment by Sikta** [comment]
So default them to 0 minutes and force them to go to the ISO tab to fill in the minutes for the ISO credit to be given. Not sure how much time prepopulating the topics really saves them but we'll do it.

**Comment by Sikta** [comment]
Is minutes a free-type field? Or should we do a dropdown with some kind of incremental selection available  (IE....15/30/45/60...etc)?

**Comment by tfremming1** [comment]
I was thinking drop down like we have it on the training stuff to keep it consistent
