### ISSUE TITLE
Creating Topics in db

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#51]
I will need a new table for topics. 

Example
Radio Communication
SCBA
etc.

In the Table I will need a column Topic and What Requirement it ties too.  This will also drive what shows up in the + section of the ISO screen

https://firesprinklerassoc.com/wp-content/uploads/2014/02/FSRS2013.pdf

Example: 
SCBA|Company Training
Railroad Ops|Hazmat Training
PPE|Company Training

Etc.

What will happen is when the ISO is filled out on the training and they select these items, it will then start populating by Fire Fighter their totals for the year.

**Comment by Sikta** [comment]
Do you have the documents you brought to lunch uploaded somewhere? I'm a little foggy on how this ties out. 

Table: Topics
Id, Name, "What requirement it ties to" - is Hazmat Training in the example a Category they already can select when creating a training so this would be the TrainingCategoryId? Or is it a completely separate table from TrainingCategory?

**Comment by Sikta** [comment]
Nevermind. https://github.com/incidentmanagementsystems/ims-issue-tracker/issues/90 answers that question.

**Comment by Sikta** [comment]
Do these table definitions look good?

IsoCategory: Id, Name, RequiredHours
IsoTopic: Id, Name, IsoCategoryId
TrainingIsoTopic (links a training to topics covered): Id, TrainingId, IsoTopicId, Minutes (because 0.33 * 3 is only going to give us 0.99 whereas 20 minutes * 3 will give us 1 hour)

**Comment by Sikta** [comment]
Is it possible for a training attendee to get partial credit for a TrainingIsoTopic?

**Comment by tfremming1** [comment]
@Sikta Yes if they left early it will be different for ISO, but that is going to have to be up to the Person entering to figure out unless you know of a programmatic way to do it.  I'm guessing that's not mvpish.  

For your first question yes I think that looks fine.
