### ISSUE TITLE
Admin - Fire Department

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#59]
**User Story:**  As an admin, I need the abillity to update the details of Agency.

Breadcrumb: `Fire Department`
Menu Option `Fire Department` under Admin to get to this page
Fields: 
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/04018363-7872-45be-9eca-d2e9afc693f7)

* Coded are dropdowns with available values sourced from IncidentLocationOption
* Number of Volunteer Firefighters is the sum of all active agents with type of volunteer for this agency
* Number of Paid Firefighters is the sum of all active agents with type of career for this agency
* Fields with an asterisk are required

**Comment by Sikta** [comment]
What does "coded" mean?

**Comment by tfremming1** [comment]
I’ll find the sheet it means standardization eg MN for Minnesota. ST for street.  

It is not wanting us to use MIN for Minnesota.  

Make sense?  I’ll find the sheet but it is standard

**Comment by Sikta** [comment]
That is what I suspected. Are we expecting for the admin to just know what their valid value is or do we need a list of valid values that they can select from in a dropdown?

**Comment by Sikta** [comment]
This is used for submitting incidents to the state? Should I really be working on this before ISO stuff? If it wouldn't bring any value until the incidents are completed, then I think we should move this into the backlog. I can work on the reports stuff until we meet to go over ISO in more detail.

**Comment by tfremming1** [comment]
I only put it here because I thought it would be a simple page and we already have some of this in db. If you feel we should do the report one and get back to this that’s fine. I’m just trying to empower the end user.  I’m fine either way 

Also no need for drop downs. When you build out validation we can make sure they are using correct value

**Comment by rkiran34** [comment]
@tfremming1 - few questions on this story - 
* RecordType is supposed to be numeric. What is it and how do users know what to enter?
* TransactionType is coded, what are the possible values? 
What do Record and TransactionType mean for an Agency?
* Number of volunteer firefighters & paid firefighters - Are these calculated using the staff(Agent) information for the agency or will the user enter these numbers?

**Comment by tfremming1** [comment]
Record Type and Transaction type can be removed

 

Yes calculate the number of fire fighters based on agency

**Comment by rkiran34** [comment]
@tfremming1 - what validation do we need on this form?

**Comment by tfremming1** [comment]
The items in the picture marked with an * are required

**Comment by rkiran34** [comment]
The document says * means definitions and abbreviations are noted in chapter 3. Do you think Prefix, Suffix, Type are required for an address? Also, shouldn't the agency name be required?

**Comment by tfremming1** [comment]
Everything with * plus agency name.

**Comment by rkiran34** [comment]
Talked to @tfremming1 - We are not going to display NumberOfVolunteerFireFighters and NumberOfPaidFireFighters for now because the logic to determine them is TBD.

Also, suffix and prefix fields are not required fields

**Comment by tfremming1** [comment]
@rkiran34 this needs to say Fire Department in the drop down.

On the page itself it also needs to say Fire Department Detail and Fire Department name.

Agency is just the dB location we are storing it.

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/9807c15b-522c-42eb-af44-3726077b491c)

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/72bfbefc-06de-4f9f-a02a-560e0e11f233)

**Comment by rkiran34** [comment]
Created a PR for this. Let me know if this is ok or if you want "Fire Department" in front of `Name` and `Id` labels
![image](https://user-images.githubusercontent.com/19315999/82729121-ab4cab00-9cba-11ea-9d3a-129cea1ceaa4.png)

**Comment by tfremming1** [comment]
Looks good
