### ISSUE TITLE
Completed Trainings UI

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#61]
When going into completed Trainings the screen is blank.  I thought it would show what was done, access to lesson plan, who attended etc.

**Comment by Sikta** [comment]
It never has because we never built a read only version of the screen. I
was going to do that but it was requested to not show complete ones in the
list.

**Comment by tfremming1** [comment]
OK sorry My mis-understanding.  I will add a card for when we move onto the staffing stuff for some kind of quick read only page.

On Jan 31, 2019, at 09:03 AM, Lee Olsen <notifications@github.com> wrote:

It never has because we never built a read only version of the screen. I
was going to do that but it was requested to not show complete ones in the
list.
