### ISSUE TITLE
Notes/Remarks Box

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#66]
I'd like to add a Notes/Remarks box to the Main Training Page.  Feedback has been that they'd like to add some remarks.  "seems" like a simple addition to make.

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/705074a6-b66f-469a-ab56-6223576e666e)

**Comment by Sikta** [comment]
What kind of character limit should we set for this?

**Comment by tfremming1** [comment]
Max 500
