### ISSUE TITLE
Incidents - Section B - Location Type

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#7]
Those with Stars in picture example are Required Fields

This top part is some background, the picture gives the layout and then under that are the particulars of the screen, and the "accepted" street codes etc.  

For these codes and "data entry" once you have it built out in the dB I can enter them in.  I do not expect you to enter all these data elements in.

Location Type 
The location of the incident, which may be a street address, directions from a recognized landmark, or an
intersection of two roadways.

Street address: A normal street address. Check or mark this box and complete the address fields.

Intersection: There is no street address. The incident location is at the intersection of two or more streets,
roads, etc. Check or mark this box and enter the first street in the Street or Highway field. The intersecting
street(s) is entered in the Cross Street or Directions field.

In front of: No street address is available. However, the incident location is in front of an area with a street
address. Check or mark this box and complete the address fields. An example of this might be a park,
plaza, or common area in front of a building with a street address.

Rear of: No street address is available. However, the incident location is in the rear of an area with a street
address. Check or mark this box and complete the address fields. An example of this might be an alley
that runs behind a building with a street address.

Adjacent to: No street address is available. However, the incident location is adjacent to an area with a
street address. Check or mark this box and complete the address fields. An example of this might be an
empty lot or common area that is next to a building with a street address.

Directions: No street address is available and no street address is available near the incident scene. Check or mark this box and enter brief directions for the location of the incident in the Cross Street or Directions
field. If the area is along an interstate or State highway, the closest milepost should be entered in the
Number/Milepost address field. An example of this might be a brush fire that occurs in a remote area
or a fire that occurs on or near an interstate highway.

United States National Grid: Provides a geospatial address based on universally defined coordinate and
grid systems and a common frame of reference across multiple jurisdictions easily extended worldwide.
Using an alpha-numeric reference that overlays the UTM (q.v.) coordinate system, USNG spatial
addresses break down into three parts: Grid Zone Designation, for a world-wide unique address;
100,000-meter Square Identification, for regional areas; Grid Coordinates, for local areas. USNG improves
interoperability of location appliances with printed maps through a consistent and preferred
geospatial grid reference system. Relates to GPS (q.v.). Contributed by Tom May. (International). For more information
and examples on use, see: http://www.xyproject.org/How%20To%20Read%20USNGHow%20
to%20read%20USNG.htm 

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/f03573c4-1533-4cdc-b884-0a95299cc4eb)

One of the biggest gripes of software out there today is that if I have gone to the address before I want it to prefill as I'm typing it.

Codes: 
Street Type:
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/53d2a07e-ec6d-4b0d-b64c-4c232d9501c3)

Prefix Codes
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/e29eeca2-5a38-4593-9fa2-fadf75840494)

Suffix Codes
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/3c1c39c2-ce88-4434-85a8-b294bb0017bf)

Page1
![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/e95b9a7f-7844-4281-bb13-4c3e8863217b)

Page 2

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/6081628e-c9ed-4b8a-bcfb-efb9fbcce7ab)

**Comment by Sikta** [comment]
```Street Type Prefix - Refer to page 3-15 a few examples:```

Do we need to do validation on things like Street Type? If yes, I assume what's in the picture isn't the full list of valid values. We need that list please.

**Comment by tfremming1** [comment]
@Sikta For Street Type if you build the field I can go in and add all the codes.

**Comment by Sikta** [comment]
Did you intend to close this?

**Comment by tfremming1** [comment]
No I didn’t. Not sure how that happened
