### ISSUE TITLE
Fire Module - Section A

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#73]
The guidance and directions for completing Section A of the Fire Module are the same as for Section A in
the Basic Module. It is stressed that the entries in Section A of the Fire Module must be identical with the
entries on the corresponding Basic Module.

In the UI - depending on how we design it, we may not have to display it (again) but it will need to be outputted to the PDF.

**Comment by Sikta** [comment]
I think we should repurpose this story for the pdf output. I don't think we'll do anything in the UI with this. Thus it could be moved to post chief conference.

**Comment by tfremming1** [comment]
You’re right it’s likely an na story I was just going down through reqs.
