### ISSUE TITLE
Main Incident Screen Look/Feel Functions

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#78]
Clicking on Incidents will lead to the main incident screen list
NOTE - Default filter should be current month

This is where you can add, view, edit etc.

If Submitted and 100% Read Only
If Not Submitted and not 100% editable by "Admin user"

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/32e085f9-1a92-4851-b8fd-52369fe30498)

**Comment by Sikta** [comment]
Can we make the filter a month/year selection or does it need a start/end date option to let them select a range?

**Comment by tfremming1** [comment]
Start end date works. What will it default to?
