### ISSUE TITLE
Clicking Save 2x fast on iPad causes double Drill to create

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#81]

**Comment by Sikta** [comment]
Ravi is working on adding the saving/loading spinner on all such operations. I think that will resolve this but don’t know how long before he is done. Will waiting for that be ok?

**Comment by tfremming1** [comment]
Waiting is fine. Just logged for tracking

**Comment by Sikta** [comment]
Btw, Ravi has completed condensing the top menu to a hamburger when on a
mobile device (not perfect but will do for now). He also completed making
it so if you go directly to a url you should be logged in for, it'll
redirect to the login and back to the page you bookmarked after login is
complete. He's currently working on the loading/saving spinner then is
going to start looking into adding SignalR so we can push to the browser
from the API (updating training attendance status without refreshing, etc).

Lee

**Comment by tfremming1** [comment]
One question. When you log in will it show the spinner. If you “wake up” the app there is some lag time. Would be nice to see something is happening etc.

**Comment by Sikta** [comment]
All save/load calls (basically every call to the api) will show the
spinner. A lot of times the response will be so fast that you probably
won't even see it pop up.
