### ISSUE TITLE
Report Page - Initial MVP

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#83]
On the Page I want it to display the name of the Fire Department (read from Fire Dept Information)

Date Picker
Click Here to download your training Data

I want it to just download everything for that FD in regards to training for the time period selected by person such that the end user can pivot off of the data.

Date
Title
Paid
Type
Method
Category
Hours
Early Departure (would normally be null but if someone has this on a drill I'd want it to show up such that it can be calculated correctly) There is an example from the February Drill for Jordan Fire that has 4 members that have diff times.
Fire Fighters Present

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/9793738d-0650-45c0-8fa1-2ef3704a435e)

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/8c9ca73e-1b9f-4e82-a60e-cd15942462e2)

**Comment by Sikta** [comment]
Would you be able to whip up an example excel file with data that you want this report to output? I want to make sure I do it right the first time so we don't waste a bunch of time going back and forth.

**Comment by tfremming1** [comment]
Yep I’ll email you here in about 30 min
