### ISSUE TITLE
Implement SSL

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#92]
Implement SSL as a part of the domain name move.

**Comment by Sikta** [comment]
I don't think this requires anything special. We are already currently using SSL.

**Comment by tfremming1** [comment]
This was likely implementing with new domain name there was a cost association.

**Comment by tfremming1** [comment]
@Sikta what did you find out from Azure do they provide this?  Or do we have to pay for one?

**Comment by Sikta** [comment]
I was able to get one from letsencrypt.com for free. They expire in 3
months but Azure had an extension that let me easily setup a web job that
automatically gets a new one and applies it before the old one expires.
