### ISSUE TITLE
Add Filtering

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#93]
On the Main Training Page and the Personnel Training Page add the following filter types

Date Picker Between Date X and Y (Default to [current month])
Type of Training

Filtering will be Key as we move into incidents as well, so lets just be sure it is consistent (on location of screen)

Show some default number of trainings per page and allow the typical first/prev/next/last with list of 5 page numbers (2 in front and 2 behind) your current page between prev/next.

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/da1f69eb-5a84-4d9e-ace4-3b9bb09051b1)

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/1ed115ee-ce91-450e-a207-3388a4f0c928)

**Comment by Sikta** [comment]
We probably need to add paging in as well. The backend supports paging already but I have to do UI work to support it. 

Options: 
1) Only allow selection of Month/Year and only show a month of trainings at a time (wouldn't need paging then)
2) Show some default number of trainings per page and allow the typical first/prev/next/last with list of 5 page numbers (2 in front and 2 behind) your current page between prev/next. 

Either way, option 2 is probably gonna need to be done for the staff list (inactive at least) at some point.

**Comment by tfremming1** [comment]
I agree #2 is the right way to go and I’m going to move to the validation release and we can add it there and then get it on the appropriate pages we already have out there and then look to add as we go forward.
