### ISSUE TITLE
Staff > Detail Training Tab update for EMR/EMT

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#96]
On Card Indicate that there is a medical component

If you can find a small image like this to put next to the status?  ![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/1a823656-a9f6-47e4-b305-482ae9381617)

In the filter section add a filter for EMR/EMT to weed out the ones that are not.

**Comment by Sikta** [comment]
If we capture this data, what are we doing with it? I don't see any stories showing how this data is used other than it showing in the UI.

**Comment by tfremming1** [comment]
Nothing for now. This is just mvp phase 1.  Capture for ease of use for emt national registry

**Comment by tfremming1** [comment]
@Sikta updated per discussion

**Comment by tfremming1** [comment]
https://fontawesome.com/icons/star-of-life?style=solid

**Comment by Sikta** [comment]
Made these changes to the training list page as well
