### ISSUE TITLE
Incident Page Layout

### ISSUE THREAD

**Issue by tfremming1** [IncidentManagementSystems/ims-issue-tracker#99]
This is about layout and tabs not the details

If section is completed tab turns green, if not started Red, in progress yellow.  

If when selecting "type" and it is an item that triggers a Main Tab that Tab to become "engaged" and turn Red"

![image.png](https://images.zenhubusercontent.com/5c34b588ea2ab97902b1bfdf/a7ad17dd-573b-43a8-a253-20bb4f42cb59)

**Comment by Sikta** [comment]
Are you wanting the fields that are configurable elsewhere to even appear on this page? IE...FDID & State

The mockup doesn't show them but the story is talking about them. I'm guessing you don't want them in the UI. We'll fill it in automatically when generating the upload.

**Comment by tfremming1** [comment]
@Sikta correct we need to account for them as a part of each incident but I don't want to display things that are not necessary e.g. FDID, State etc.  I want to keep it as clean as possible as long as data is in dB we are good.
